excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kevin-insight.github.io
title: Kevin McGillivray
tagline: A log of everyday life
description: My awesome new site
paginate: 5